baseURL: http://janavmakkar.com/
languageCode: en-us
title: IT is fun
theme: "papermod"

googleAnalytics: G-T92C1K135S

menu: 
  main:
    # - identifier: how-to
    #   name: How-To'sğŸ¤”
    #   url: /how-to/
    #   weight: 10
    # - identifier: cheatsheet
    #   name: CheatsheetsğŸ“œ
    #   url: /cheatsheet/
    #   weight: 20
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
      # - how-to's, cheatsheets, advice, problem-solving
    - identifier: all-posts
      name: All Posts
      url: /all-posts/
      weight: 30
    - identifier: tags
      name: TagsğŸ·ï¸
      url: /tags/
      weight: 40

params:
    homeInfoParams:
        Title: Hi there ğŸ‘‹
        Content: Welcome to Janav's blog

    socialIcons: # optional
        - name: "Linkedin"
          url: "https://www.linkedin.com/in/janav-makkar-417871179/"
        - name: "Github"
          url: "https://github.com/janavmakkar"
        - name: "Twitter"
          url: "https://twitter.com/janav_makkar"
    
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowShareButtons: [â€œlinkedinâ€, â€œtwitterâ€]
    ShowReadingTime: true


    assets:
        favicon: /favicon/favicon.ico
        favicon16x16:  /favicon/favicon-16x16.png
        favicon32x32:  /favicon/favicon-32x32.png
        apple_touch_icon:  /favicon/apple-touch-icon.png
        # safari_pinned_tab:  /favicon/

