baseURL: http://janavmakkar.com/
languageCode: en-us
title: IT is fun
theme: "papermod"

googleAnalytics: G-T92C1K135S

menu: 
  main:
    - identifier: how-to
      name: How-To'sğŸ¤”
      url: /how-to/
      weight: 10
    - identifier: cheatsheet
      name: CheatsheetsğŸ“œ
      url: /cheatsheet/
      weight: 20
    - identifier: tags
      name: TagsğŸ·ï¸
      url: /tags/
      weight: 30
    - identifier: categories
      name: CategoriesğŸ§º
      url: /categories/
      weight: 40

params:
    homeInfoParams:
        Title: Hi there ğŸ‘‹
        Content: Welcome to Janav's blog

    socialIcons: # optional
        - name: "Linkedin"
          url: "https://www.linkedin.com/in/janav-makkar-417871179/"
        - name: "Github"
          url: "https://github.com/janavmakkar"
        - name: "Twitter"
          url: "https://twitter.com/janav_makkar"
